version: '3.9'

services:
  quasar-app: 
    build: ./voting-websocket-app
    container_name: spa
    ports:
      - 8888:8888
    networks:
      - web-aula
    volumes:
      - ./voting-websocket-app:/app
    command: ['yarn', 'quasar', 'dev']

  server: 
    image: nginx:1.21.1
    container_name: nginx-web
    ports:
      - 80:80
    networks:
      - web-aula
    volumes:
      - ./confs/servers:/etc/nginx/conf.d/
      - ./voting-websocket-api:/var/www/html

  api: 
    build: ./voting-websocket-api
    container_name: voting-api
    ports:
      - 9000:9000
    networks:
      - web-aula
    volumes:
      - ./voting-websocket-api:/var/www/html

  socket:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    environment:
            SOKETI_DEBUG: '1'
            SOKETI_METRICS_SERVER_PORT: '9601'
    container_name: socket
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    networks:
      - web-aula

  db-redis:
    image: 'redis:7.2.3-alpine'
    container_name: db-redis
    ports:
      - 6379:6379
    networks:
      - web-aula

  db:
    image: mysql:5.7
    container_name: db
    volumes: 
      - ./confs/mysql_db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voting
    ports:
      - 3306:3306
    networks: 
      - web-aula

networks: 
  web-aula:
    driver: bridge
